#!/usr/bin/python3

from sys import stdin
from string import ascii_lowercase as chars
from random import randint, choice
from operator import itemgetter
from collections import defaultdict


def counting_sort(A, d, key=lambda x: x):
    B, C = [], defaultdict(list)
    for x in A:
        C[key(x[0])].append(x)
    #for i in range(ord(min(C)), ord(max(C))+1):
        #B.extend(C[chr(i)])
    return C

def flexradix(A, d):
    n = len(A)
    C = counting_sort(A, 0);

def main():
    d = int(stdin.readline())
    strings = []
    for line in stdin:
        strings.append(line.rstrip())
    A = flexradix(strings, d)
    print(A)
    for string in A:
        print(string)


if __name__ == "__main__":
    main()
